// AUTO-GENERATED — do not edit by hand.
// Regenerate with: plasmoid/gen-defaults.py
// Source: package/contents/config/main.xml
.pragma library

var defaults = {
    pollingInterval: 1500,
    showLastTranscription: true,
    previewMode: false,
    audioContext: false,
    pinPopup: false,
    noiseGate: 0.05,
    envelopePower: 1.0,
    envelopeCenter: 0.5,
    audioSensitivity: 2.0,
    barSensitivity: 2.0,
    waveSensitivity: 2.0,
    pulseSensitivity: 2.0,
    dotSensitivity: 2.0,
    useRainbow: false,
    rainbowStartHue: 0,
    rainbowEndHue: 270,
    animationStyle: "bars",
    barCount: 15,
    barSpacing: 2,
    barRadius: 1,
    barMinHeight: 0.2,
    barIdleAnimation: false,
    animationSpeed: 300,
    waveWidth: 80,
    waveThickness: 3,
    waveFrequency: 2.0,
    waveAmplitude: 0.8,
    waveSpeed: 400,
    waveFill: true,
    pulseRings: 3,
    pulseThickness: 2,
    pulseSpeed: 800,
    waveformBars: 17,
    waveformSpacing: 2,
    waveformRadius: 2,
    waveformMinHeight: 0.1,
    waveformSensitivity: 2.0,
    dotCount: 9,
    dotSize: 6,
    dotBounce: 40,
    dotSpacing: 3,
    dotSpeed: 400,
}
